### ISSUE TITLE
DynamicModule is not assignable to type 

### ISSUE THREAD

**Issue by heshuai326** [kyknow/nestjs-redis#19]
`
import { RedisModule } from 'nestjs-redis';

@Module({
  imports: [
    RedisModule.register({
      name: '',
      host: '',
      port: 6379,
      db: 1,
      password: '',
      keyPrefix: '_dream'
    }),
})

return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/app.module.ts(33,5): error TS2322: Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.
  Type 'import("E:/serve/node_modules/nestjs-redis/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule' is not assignable to type 'import("E:/serve/node_modules/@nestjs/common/interfaces/modules/dynamic-module.interface").DynamicModule'.
    Types of property 'imports' are incompatible.
      Type '(DynamicModule | Type<any> | Promise<DynamicModule> | ForwardReference<any>)[]' is not assignable to type '(Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>)[]'.
        Type 'DynamicModule | Type<any> | Promise<DynamicModule> | ForwardReference<any>' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.
          Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.

    at createTSError (E:\serve\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (E:\serve\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (E:\serve\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (E:\serve\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\serve\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

I use yarn to instead of npm but the error  still
yarn add nestjs-redis -S
(https://github.com/kyknow/nestjs-redis/issues/11)

**Comment by andrii33** [comment]
I believe that happened because of the different versions of the nestjs in your app and module.

The Redis module uses version 6 https://github.com/kyknow/nestjs-redis/blob/master/package.json#L24
And your app is probably 8 or 9
